version: '3.9'
services:
  app:
    build:
      context: .
    ports:
      - "8080:8080"
    restart: on-failure
    depends_on:
      - webhooks
      - db
    networks:
      - upgate_client
    env_file:
      - .env
  webhooks:
    image: webhooksite/cli:latest
    command: whcli forward --token=60b2e73b-1914-4ed5-aaf0-354712d0355e --api-key=1115b450-fa58-47d6-b94b-d25b9e948771 --target=http://app:8080/callback
    networks:
      - upgate_client
  db:
    image: postgres:15-alpine3.19
    ports:
      - "5432"
    environment:
      - POSTGRES_PASSWORD=postgres
    volumes:
      - ./dev/initdb/init.sql:/docker-entrypoint-initdb.d/init.sql
      - pg_data:/var/lib/postgresql/data
    networks:
      - upgate_client

networks:
  upgate_client:

volumes:
  pg_data:
